FROM ubuntu:18.04

RUN apt update && \
    apt install -y curl

WORKDIR /app/
COPY  myapp.sh ./


RUN chmod +x ./myapp.sh

#? ARREGLO: recomendada
ENTRYPOINT  ["./myapp.sh"]

CMD []


# ! NO SE LAS RECOMIENDO
#CMD "bash /app/myapp.sh"

